version: '3'

services:
  db:
    image: "postgres"
    restart: "no"
    env_file:
      - .env
    ports:
    - 5432:5432
    volumes:
    - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
